In [31]:
import tensorflow as tf
import random 
import numpy as np

#1
scalar = tf.constant(7)
vector = tf.constant([5, 6])
matrix = tf.constant([[1, 2], [3, 4]])

#2
print(scalar.ndim)
print(vector.ndim)
print(matrix.shape)
print(tf.size(matrix).numpy())

#3
some_tensor1 = tf.constant([[random.random() for i in range(300)] for j in range(5)])
some_tensor2 = tf.constant([[random.random() for i in range(300)] for j in range(5)])
print(some_tensor1.shape)

#4, 5
multiplied_tensor = some_tensor1 * some_tensor2
#multiplied_tensor2 = tf.matmul(some_tensor1, some_tensor2)
tf.multiply(some_tensor1, 10)

#6
another_tensor = tf.constant([[[random.random() for i in range(3)] for j in range(224)] for n in range(224)])
print(another_tensor.shape)

#7
print(tf.reduce_min(another_tensor).numpy())
print(tf.reduce_max(another_tensor).numpy())

#8
another_tensor2 = tf.constant(np.random.randint(0, 10, 150528), shape=(1, 224, 224, 3))
print(another_tensor2.shape)
another_tensor2_squeezed = tf.squeeze(another_tensor2)
print(another_tensor2_squeezed.shape)

#9
task_nine_tensor = tf.constant([5, 4, 5, 10, 2, 4, 6, 1, 8, 3])
print(tf.argmax(task_nine_tensor).numpy())

#10
print(tf.one_hot(task_nine_tensor, depth=11))

0
1
(2, 2)
4
(5, 300)
(224, 224, 3)
5.6395714e-07
0.99999124
(1, 224, 224, 3)
(224, 224, 3)
3
tf.Tensor(
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 11), dtype=float32)
